### ISSUE TITLE
About encoding result on random images

### ISSUE THREAD

**Issue by pnbao** [genforce/idinvert#10]
Thank you for your great work!!

I have tested the model with some random images from internet, the encoding results and manipulation results is not really good as compared to other images included in your examples folders.

<img width="2528" alt="Screen Shot 2020-08-06 at 15 16 46" src="https://user-images.githubusercontent.com/11147999/89497941-46541c00-d7f8-11ea-9085-181f4bb82244.png">

<img width="2537" alt="Screen Shot 2020-08-06 at 15 15 27" src="https://user-images.githubusercontent.com/11147999/89498012-6257bd80-d7f8-11ea-8e94-1cd03a2b0ed1.png">

How can I improve the model for better encoding images like those?

For the interpolation, can we adjust the copied style range to interpolate coarse style, middle style and fine style? 
![image](https://user-images.githubusercontent.com/11147999/89503459-84097280-d801-11ea-8ae4-3e11898a9634.png)

By the way, the model trained based on StyleGAN, so can the encoded latent can be fed into a StyleGAN generator?

**Comment by ShenYujun** [comment]
Faces should be pre-aligned before fed into the encoder. Please refer to [this link](https://github.com/NVlabs/ffhq-dataset/blob/bb67086731d3bd70bc58ebee243880403726197a/download_ffhq.py#L259).

Our encoder is based on a StyleGAN model trained on FF-HQ with 256 resolution. The official model is with 1024 resolution. So, they may mismatch. Furthermore, we use a StyleGAN generator that uses different `w`s for different layers. This is a little bit different from the original StyleGAN generator that uses the same `w` for all layers.
