### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mengyuxin520** [genforce/idinvert#11]
When I try to train the generator, the error appears as below:

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    import dnnlib
  File "/stylegan/dnnlib/__init__.py", line 20
    submit_config: SubmitConfig = None # Package level variable for SubmitConfig which is only valid when inside the run function.
                 ^
SyntaxError: invalid syntax

Could you give me some advice?

**Comment by zhujiapeng** [comment]
Here is a solution https://stackoverflow.com/questions/57145923/implementation-of-stylegan-by-nvlabs-shows-syntax-error.

**Comment by mengyuxin520** [comment]
I set python 3.7 and the latest tensorflow version. Is there else environment I need?

**Comment by zhujiapeng** [comment]
In repo's README.md file, we offered the environment (as shown in red rectangle) we run the code.
![捕获](https://user-images.githubusercontent.com/10594850/89778474-2c8c3f00-db40-11ea-8783-bd740823bc7c.PNG)
