### ISSUE TITLE
the number of optimization iteration

### ISSUE THREAD

**Issue by blandocs** [genforce/idinvert#17]
Thank you for your great works again :)

I'm curious about the number of optimization iteration.

In your code, it is 100 iterations, but in the paper the optimization process consumes 142s per image.

What is the number of optimization iteration in your paper?

Thank you in advance.

**Comment by ShenYujun** [comment]
We found that 100 iterations are enough to produce satisfying results. Hence in the latest version of our [paper](https://arxiv.org/pdf/2004.00049.pdf), we update the time to 8s.

**Comment by blandocs** [comment]
Thank you for your reply :)

Have a great day!
