### ISSUE TITLE
Training encoder for 1024x1024 images

### ISSUE THREAD

**Issue by aiXander** [genforce/idinvert#18]
I wanted to try and train an encoder for the full HD 1024x1024 images.

- Is there a reason this was not attempted in the paper?
- Upon doing this, the encoder network becomes insanely large (236M params) since the input shape to the final FC layer is now huge

**Comment by zhujiapeng** [comment]
Training 1024x1024 images cost too much time and GPU memory. Currently, we try to optimize the encoder's structure to solve this.
