### ISSUE TITLE
Some problems for training encoder.

### ISSUE THREAD

**Issue by Daic115** [genforce/idinvert#2]
Hey man, thanks for your great work! I have some problems during training encoder. I'd really appreciate it if you could anwser me the following questions：
1. What is the minimum GPU requirement for training encoder?
2. And can you tell me more details of the results of Table 1 in your paper? How much training iters for Domain-guided Encoder and for In-domain Inversion.

Thank you very much!

**Comment by zhujiapeng** [comment]
1. If you use the default setting in `train_encoder.py` script, e.g., training a 256x256 size images model, the minimum GPU memory is 16G, you could change the batch_size according to your GPU memory.
2. We use 14000 kimg for training the Domain-guided Encoder (the default setting in `train_encoder.py`), and 1000 iterations for In-domain Inversion.

**Comment by Daic115** [comment]
Thanks！By the way, how long did it take for training1000 epoch with Domain-guided Encoder？I may have to examine whether my GPU can be used for so long XD.

**Comment by zhujiapeng** [comment]
On 8 GeForce RTX 2080 Ti GPUs, it takes about two and a half days.
