### ISSUE TITLE
Problems about training encoder

### ISSUE THREAD

**Issue by Hsintien-Ng** [genforce/idinvert#22]
We have applied the train_encoder.py file for other datasets with the provided settings. But we got image with nan value after several steps. Have you met such a problem?

Another question about loading encoder is that when we load the pretrained weights of the network file (face_256x256) you provided, the process stuck at line "_, recon_, adv_ = sess.run([E_train_op, E_loss_rec, E_loss_adv], feed_dict)". Also, we met "v10:  {'is_template_graph': False, 'components': {}}" when constructing the graph.

**Comment by zhujiapeng** [comment]
1. I don't know what kind of dataset you are using, I don't meet such a problem.
2. The `.pkl` files will save the network code I used during training, and when to load the saved `.pkl`, it will use the code save in it, the "v10..." info is the debug info I printed during training. I used 8 GPUs to train the encoder, so for simplicity, you could train the pre-trained model using 8 GPUs or you need to specify the GPUs you using.
