### ISSUE TITLE
colab issue

### ISSUE THREAD

**Issue by ghost** [genforce/idinvert#23]
EOFError                                  Traceback (most recent call last)
<ipython-input-5-7c3d9c8db416> in <module>()
      1 inverter = build_inverter(model_name, iteration=100,
----> 2                           regularization_loss_weight=0)
      3 output.clear()
      4 print('Upload the target image you want to diffuse or use the default image by clicking `Cancel upload` button.')
      5 uploaded = files.upload()

7 frames
/usr/local/lib/python3.6/dist-packages/torch/serialization.py in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
    753             "functionality.".format(type(f)))
    754 
--> 755     magic_number = pickle_module.load(f, **pickle_load_args)
    756     if magic_number != MAGIC_NUMBER:
    757         raise RuntimeError("Invalid magic number; corrupt file?")

EOFError: Ran out of input

**Comment by zhujiapeng** [comment]
This is because the weights can't be download correctly, we have updated the weights links.

**Comment by ghost** [comment]
thanks

**Comment by ghost** [comment]
@zhujiapeng could you please add a video interpolation code in the colab?
