### ISSUE TITLE
What is the image range when calculating the mean square error?

### ISSUE THREAD

**Issue by gsygsy96** [genforce/idinvert#29]
@ShenYujun, it's a little confuse.

**Comment by ShenYujun** [comment]
It should be [-1, 1].

**Comment by gsygsy96** [comment]
Get it. Thanks.

**Comment by gsygsy96** [comment]
BTW, how to statistic the speed? One way is to calculate the time required for a minibatch and then process the number of minibatch. Is that the way? Thank you for your guidance

**Comment by ShenYujun** [comment]
Yes, you are right. But a more accurate way is to set the minibatch as 1.

**Comment by gsygsy96** [comment]
Get it! thanks!
