### ISSUE TITLE
A pretrained stylegan-ffhq-256x256 model for training new encoder 

### ISSUE THREAD

**Issue by fungtion** [genforce/idinvert#30]
Hi, I want to train a new encoder, but I can not find a pretrained Gs model, i.e. stylegan-ffhq-256x256.pkl, only stylegan-ffhq-1024x1024.pkl avaliable，so how can I get this model? Thanks

**Comment by ShenYujun** [comment]
All pre-trained models are available in the repo. [Here](https://drive.google.com/file/d/1azAzSZg6VfNydjWr4qfl8Z4LfxktTPqM/view?usp=sharing) is the ffhq-256 model.

**Comment by fungtion** [comment]
Thanks.
