### ISSUE TITLE
Some questions for "Semantic Analysis of the Inverted Codes" in the paper?

### ISSUE THREAD

**Issue by GreenLimeSia** [genforce/idinvert#32]
I want to know how to use boundaries to evaluate the attribute classification performance using the inverted codes? In addition, would you mind sharing this code and the off-the-shelf classifier?

![1604922263(1)](https://user-images.githubusercontent.com/28706611/98538147-49fab180-22c5-11eb-8a08-2f7179519ea2.png)

![1604923013(1)](https://user-images.githubusercontent.com/28706611/98538509-d2795200-22c5-11eb-9fff-4ca5c5702fd9.jpg)

**Comment by ShenYujun** [comment]
Given the boundary, you can compute the distance from a code (corresponding to a synthesis) to this boundary, as the data. Meanwhile, you can get the semantic score for the synthesis, as the label. With such data-label pairs, you can draw the precision-recall curve like in the paper.

**Comment by GreenLimeSia** [comment]
Thanks for your reply! How to compute the distance from a code to an attribute boundary, by using a cos(x)? I think cos(x) maybe perform well since it outputs a score with [0,1], when score=1, only and only if orthogonal. I summary some ideas for evaluating the semantics: 
1、Training a classifier that can predict arbitrary image labels, and the predict labels as ground truth. The same idea as your paper.
2、Sampling latent code and generating its corresponding images, and predict that images label. Then we have pairs data (latent code, labels).
3、Obtain a linear model with input latent code and output labels.
4、Using the well-trained linear model to predict inverse code with different methods, compute accuracy between predicting labels and ground truth.
What do you think of this idea?

**Comment by ShenYujun** [comment]
1. We compute the score between a particular latent code and a semantic boundary with Euclidean distance.

2. Your pipeline is correct!

**Comment by GreenLimeSia** [comment]
Thanks for your reply!  I will cite your hard work!
