### ISSUE TITLE
train model for different $w$

### ISSUE THREAD

**Issue by betterze** [genforce/idinvert#4]
Thank you for your great work. I have a simple question.

In the training section, you mention that 'change repleated $w$ for all layers to different $w$s'. There are a few pretrained models in [stylegan](https://github.com/NVlabs/stylegan) which use repleated $w$, could I just adapt the weights from them or I need to retrain the model?

Thank you for your help.

**Comment by betterze** [comment]
And would you mind uploading the manipulation boundary for face? Thank you again for your help.

**Comment by betterze** [comment]
any response?

**Comment by ShenYujun** [comment]
> And would you mind uploading the manipulation boundary for face? Thank you again for your help.

Sorry, but the `npy` boundaries are ignored by git before. Now, all boundaries are uploaded.

**Comment by ShenYujun** [comment]
> Thank you for your great work. I have a simple question.
> 
> In the training section, you mention that 'change repleated $w$ for all layers to different $w$s'. There are a few pretrained models in [stylegan](https://github.com/NVlabs/stylegan) which use repleated $w$, could I just adapt the weights from them or I need to retrain the model?
> 
> Thank you for your help.

Although we recommend using different `w`s for different layers, using same `w` (i.e., the official StyleGAN) also works. You can use the official StyleGAN model and then use IDInvert to train your own encoder and use InterFaceGAN to find your own boundaries.

**Comment by 250906461** [comment]
> > And would you mind uploading the manipulation boundary for face? Thank you again for your help.
> 
> Sorry, but the `npy` boundaries are ignored by git before. Now, all boundaries are uploaded.

Thx, I will try it.

**Comment by betterze** [comment]
> > And would you mind uploading the manipulation boundary for face? Thank you again for your help.
> 
> Sorry, but the `npy` boundaries are ignored by git before. Now, all boundaries are uploaded.

Thanks a lot, I will try it.
