### ISSUE TITLE
CUDA, cuDNN and NCCL versions

### ISSUE THREAD

**Issue by basitanees** [genforce/idinvert#46]
Hi,

I am using 2 Tesla v100s. My program gets killed when using mode than 1 gpu.
![Screenshot 2021-05-07 082333](https://user-images.githubusercontent.com/50206820/117396163-d6073200-af12-11eb-95cf-8171f140b234.png)

When using 8 Tesla_t4, it gets killed as well (with some memory errors which were removed by allowing growth and limiting memory fraction)
![Screenshot 2021-05-06 174203](https://user-images.githubusercontent.com/50206820/117396204-ecad8900-af12-11eb-8e63-386bbf1c42c2.png)

My guess is it could be due to incompatibility issues. Which version of CUDA, cuDNN and NCCL versions are you using for your implementation? I am currently using:
- CUDA-11.0
- cuDNN 7.0.6-cuda-10.1
- NCCL 2.9.6-1/cuda-10.2

Any help would be appreciated.

Regards,

**Comment by zhujiapeng** [comment]
You could try with CUDA=10.0, cudnn=7.6.4, tensorflow-gpu==1.12.0.

**Comment by basitanees** [comment]
Thank you for your feedback. It was actually related to CPU RAM. Increasing the RAM solved the issue while using your mentioned cuda and tensorflow versions.
