### ISSUE TITLE
My own data set

### ISSUE THREAD

**Issue by KramerKonstantin** [genforce/idinvert#48]
Hello, I'm new to this and I need your help.
I trained StyleGAN on my own dataset, using your scripts in [genforce](https://github.com/genforce/genforce).
Now I need to learn how to invert images to the StyleGAN latent space, that is, I want to get styleganinv, what do I need for this?

**Comment by zhujiapeng** [comment]
Follow `Step-1` and `Step-2` in the README.md file.
