### ISSUE TITLE
more training examples for manipulation 

### ISSUE THREAD

**Issue by 250906461** [genforce/idinvert#5]
Dear Genforce group,

Thank you for your great work, I really like your work 'in-domain gan'.

As you state in the paper, in order to do image manipulation (male -> female), you use [interfacegan](https://github.com/genforce/interfacegan) to find the manipulation direction in wp, w or z. Since you use wp which is 14x more dimentions than w, you will need to generate more data to train the linear SVM, right? Interfacegan manipulates on w and train svm with 500k generated images, how many images you need to train svm on wp?

Notice that interfacegan uses standard stylegan, and wp is just broadcasting of w, they have the same intrinsic dimentions, so it can use the same amount of images to train on either w or wp. But in 'in-domain gan', you retrain the stylegan with different w instead of repeated w, so wp has larger intrinsic dimentions than each w.

Looking forward for your reply. Thanks in advance.

**Comment by ShenYujun** [comment]
Actually, we can use the same number of samples for boundary training. Please refer to [this issue](https://github.com/genforce/interfacegan/issues/38). You can still treat the w codes for 14 layers independently. In this way, it is exactly the same as InterFaceGAN. Please see HiGAN for the details of layer-wise manipulation.

**Comment by 250906461** [comment]
Thx, your answer is very helpful.
