### ISSUE TITLE
FID metrics

### ISSUE THREAD

**Issue by blandocs** [genforce/idinvert#7]
First of all, thank you for your great works!

I'm curious about your FID metrics (Table 1 in your paper).
Did you compare 500 fake images with 50000 real images? 
It seems to that because of high FID scores.

If so, wouldn't it better comparing 500 fake images and corresponding 500 real images?

![image](https://user-images.githubusercontent.com/11532292/84473893-ceb8b380-acc4-11ea-8e8c-956934fe0bbe.png)

Thank you :)

**Comment by zhujiapeng** [comment]
We randomly chose 500 images from FFHQ, and get the corresponded reconstructed images, and then calculates the FID metrics using those images. By the way, we chose 500 images to calculate FID just to save some time.

**Comment by blandocs** [comment]
That's quite reasonable. Thank you for your prompt response!

**Comment by blandocs** [comment]
Hi there! I have another questions. 

1. Your encoder and styleGAN used full 70K FFHQ images for training. But you chose 500 images from FFHQ for evaluation. So, there is no separation between training and test dataset. Do I understand correctly? Have you tried testing reconstruction on other dataset like CelebaHQ?

2. How did you compare with Image2StyleGAN [24]? Authors do not offer codes... Did you use [unofficial repository](https://github.com/pacifinapacific/StyleGAN_LatentEditor)?

Thank you in advance :)

**Comment by zhujiapeng** [comment]
1. We split the 70k images into 65k training images and 5k testing images. We found inverting 5k images using Image2StyleGAN costs too much time. So we randomly chose 500 images from testing images.
2. The author gave their codes to me...

**Comment by blandocs** [comment]
Thank you for your kindness :)
