### ISSUE TITLE
How to preprocess LSUN?

### ISSUE THREAD

**Issue by gsygsy96** [genforce/idinvert#9]
Hi Yujun @ShenYujun. Facial images need to be aligned first. But I don't know how to preprocess LSUN's images. Directly resizing them to 256 x 256?

**Comment by ShenYujun** [comment]
Yes. No need to resize LSUN images.

**Comment by gsygsy96** [comment]
No need to resize LSUN images? But some of the images are not squares, but rectangles, like 256x350.
Sorry, I'm puzzled about this.

**Comment by ShenYujun** [comment]
Sorry, it should be center cropping and resizing. Please refer to [this link](https://github.com/NVlabs/stylegan/blob/66813a32aac5045fcde72751522a0c0ba963f6f2/dataset_tool.py#L406).

**Comment by gsygsy96** [comment]
Thanks for your help!
